sudo: false
language: node_js
node_js:
  - 10.16.2
install:
  - npm install
script:
  - npm test
after_success: npm run coverage
services:
  - postgresql
before_script:
  - psql -c 'create database mydiarydb;' -U postgres
after_success:
  - npm run coverage
